import numpy as np

N = 100

lam = 1
eps = N**2 / (8 * np.pi**2 * lam)

lower = np.zeros((N, N), dtype=np.float64)
upper = np.zeros((N, N), dtype=np.float64)
np.fill_diagonal(lower, -1)
np.fill_diagonal(upper, -1)
lower = np.roll(lower, -1, axis=1)
upper = np.roll(upper, 1, axis=1)

U = lower + upper
np.fill_diagonal(U, 2)
U *= eps

n = np.arange(N)
phi_n = 2 * np.pi * n / N
V = lam * np.diag(1 - np.cos(phi_n))

# --- 

I = np.eye(N)

U1 = np.kron(U, I)
U2 = np.kron(I, 2*U)
V1 = np.kron(V, I)
V2 = np.kron(I, V)

# cross terms are generated by "brute force" instead of an otimes  
phi1_grid, phi2_grid = np.meshgrid(phi_n, phi_n, indexing='ij')
V12 = lam * (1 - np.cos(phi1_grid - phi2_grid))
V12 = np.diag(V12.flatten()) # fix the shape

# ---

H = (U1 + U2) + (V1 + V2) + V12
eigvals = np.linalg.eigvalsh(H)
print(f"eigvals = {np.round(eigvals[0::N], 4)}") # N degeneracy?!
