#!/usr/bin/env bash

# Ensure the script is called with an argument
if [ -z "$1" ]; then
  echo "Usage: $0 <title>"
  exit 1
fi

tectonic -X new
cat << EOF > src/_preamble.tex
\documentclass{article}

\newcommand{\labTitle}{$1}
\newcommand{\labDueDate}{\today}
\newcommand{\labClass}{PHSX 531}
\newcommand{\labAuthorName}{\textbf{Grant Saggars}}

\usepackage{fancyhdr}
\usepackage{extramarks}
\usepackage{amsmath}
\usepackage{amsthm}
\usepackage{amsfonts}
\usepackage{tikz}

\usepackage{float}
\usepackage{caption}
\usepackage{bbold}
\usepackage{xcolor}
\usepackage{framed}
\usepackage{enumerate}
\usepackage{cancel}
\usepackage{multicol}
\usepackage{XCharter}
\usepackage{pgfplots}
\usepackage{braket}

\usetikzlibrary{automata,positioning}

\usepackage{geometry}
\geometry{top=1in, bottom=1in, left=1in, right=1in} % Adjust margins as needed

\pagestyle{fancy}
\lhead{\labAuthorName}
\chead{\labClass\: \labTitle}
\rhead{\firstxmark}
\lfoot{\lastxmark}
\cfoot{\thepage}

%
% Basic Document Settings
%

\topmargin=-0.75in
\evensidemargin=0in
\oddsidemargin=0in
\textwidth=6.5in
\textheight=9.0in
\headsep=0.25in

\linespread{1.1}

\renewcommand\headrulewidth{0.4pt}
\renewcommand\footrulewidth{0.4pt}

\setlength\parindent{0pt}

%
% Callout Box
%

\definecolor{shadecolor}{RGB}{235,235,235}
\newenvironment{callout}[1] {\begin{shaded*} \textbf{#1}} {\end{shaded*}}

%
% Title Page
%

\title{
    \textmd{\textbf{\labClass:\ \labTitle}} \\\\
    \normalsize\vspace{0.1in}\small{\labDueDate} \\
}

\author{\labAuthorName}
\date{}

\makeatletter
\let\orig@section\section
\renewcommand{\section}[1]{%
    % Set up the marks for continued sections
    \nobreak\extramarks{#1}{#1 continued on next page\ldots}\nobreak{}%
    % Make the section
    \orig@section{#1}%
    % Set the marks for the new section
    \nobreak\extramarks{#1}{#1 continued on next page\ldots}\nobreak{}%
}
\makeatother

% Define the header style
\pagestyle{fancy}
\fancyhead[R]{\firstxmark}

\begin{document}
\maketitle
EOF
